"""Monitoring: input drift, score drift and the monthly calibration update.

Population Stability Index (PSI) compares a feature's distribution in a current batch with a
reference (the training data), using the reference's quantile bins. Missing values get their own
bin, so a change in how often a feature is undefined also shows up. Conventional reading:
< 0.1 stable, 0.1 to 0.25 moderate shift, > 0.25 major shift.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from ttr.evaluate.calibration import intercept_shift

PSI_MODERATE, PSI_MAJOR = 0.1, 0.25
_EPS = 1e-4


def psi(reference: pd.Series, current: pd.Series, bins: int = 10) -> float:
    ref, cur = reference.astype(float), current.astype(float)
    edges = (
        np.unique(np.nanquantile(ref, np.linspace(0, 1, bins + 1)[1:-1]))
        if ref.notna().any()
        else np.array([])
    )

    def shares(x: pd.Series) -> np.ndarray:
        idx = np.where(x.isna(), len(edges) + 1, np.searchsorted(edges, x, side="right"))
        counts = np.bincount(idx.astype(int), minlength=len(edges) + 2)
        out: np.ndarray = np.clip(counts / max(len(x), 1), _EPS, None)
        return out

    r, c = shares(ref), shares(cur)
    return float(np.sum((c - r) * np.log(c / r)))


def status(value: float) -> str:
    if value > PSI_MAJOR:
        return "major"
    if value > PSI_MODERATE:
        return "moderate"
    return "stable"


def feature_drift(
    reference: pd.DataFrame, current: pd.DataFrame, features: list[str]
) -> pd.DataFrame:
    rows = [{"feature": f, "psi": psi(reference[f], current[f])} for f in features]
    out = pd.DataFrame(rows).sort_values("psi", ascending=False).reset_index(drop=True)
    out["status"] = out["psi"].map(status)
    return out


@dataclass(frozen=True)
class MonitoringResult:
    features: pd.DataFrame
    score_psi: float
    probability_mean_reference: float
    probability_mean_current: float
    recommended_shift: float | None


def monitor(
    reference: pd.DataFrame,
    current: pd.DataFrame,
    features: list[str],
    ref_scores: pd.DataFrame,
    cur_scores: pd.DataFrame,
    outcomes: pd.DataFrame | None = None,
) -> MonitoringResult:
    """Drift of inputs and scores; with ``outcomes`` (columns probability, y, w for the latest
    month whose outcomes are complete), also the recommended intercept shift."""
    shift = None
    if outcomes is not None and len(outcomes):
        shift = intercept_shift(
            outcomes["probability"].to_numpy(), outcomes["y"].to_numpy(), outcomes["w"].to_numpy()
        )
    return MonitoringResult(
        features=feature_drift(reference, current, features),
        score_psi=psi(ref_scores["risk_score"], cur_scores["risk_score"]),
        probability_mean_reference=float(ref_scores["probability"].mean()),
        probability_mean_current=float(cur_scores["probability"].mean()),
        recommended_shift=shift,
    )


def monitoring_markdown(
    result: MonitoringResult, reference_name: str, current_name: str, top: int = 10
) -> str:
    counts = result.features["status"].value_counts()
    table = "\n".join(
        f"| `{r.feature}` | {r.psi:.3f} | {r.status} |"
        for r in result.features.head(top).itertuples()
    )
    shift = (
        f"{result.recommended_shift:+.3f} (logit scale)"
        if result.recommended_shift is not None
        else "n/a (no complete outcomes supplied)"
    )
    mix = " / ".join(str(counts.get(k, 0)) for k in ("stable", "moderate", "major"))
    means = f"{result.probability_mean_reference:.4f} -> {result.probability_mean_current:.4f}"
    return f"""# Monitoring: {current_name} vs {reference_name}

Generated by `ttr monitor`. PSI < {PSI_MODERATE} stable, {PSI_MODERATE} to {PSI_MAJOR}
moderate, > {PSI_MAJOR} major.

| | |
|---|---|
| Features stable / moderate / major | {mix} |
| Risk-score PSI | {result.score_psi:.3f} ({status(result.score_psi)}) |
| Mean 30-day probability (unweighted rows) | {means} |
| Recommended intercept shift | {shift} |

## Most-shifted features

| Feature | PSI | Status |
|---|---|---|
{table}
"""
