"""Offline evaluation of note writers on scored players.

For the top-``n`` players by risk at a landmark, write a note with the chosen writer and record
whether it passed the guard, why not, and what it cost. Notes with player values go to a JSONL
file (keep it out of git for licensed data); the summary is aggregate only.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from ttr.notes.facts import player_facts
from ttr.notes.schema import NoteResult
from ttr.notes.writer import NoteWriter
from ttr.serve.scoring import Scorer, describe

# USD per million tokens (input, output); used only for the cost estimate in the report.
PRICES = {
    "claude-opus-5-5": (4.0, 20.0),
    "claude-sonnet-5-5": (2.0, 10.0),
    "claude-haiku-4-5": (1.0, 5.0),
}


@dataclass(frozen=True)
class NotesEvaluation:
    results: list[NoteResult]
    landmark: pd.Timestamp

    @property
    def sources(self) -> Counter[str]:
        return Counter(r.source for r in self.results)

    @property
    def violations(self) -> Counter[str]:
        return Counter(v.split(":")[0] for r in self.results for v in r.violations)

    def cost_usd(self) -> float | None:
        priced = [r for r in self.results if r.model in PRICES and r.input_tokens is not None]
        if not priced:
            return None
        return sum(
            (r.input_tokens or 0) * PRICES[str(r.model)][0] / 1e6
            + (r.output_tokens or 0) * PRICES[str(r.model)][1] / 1e6
            for r in priced
        )


def evaluate_notes(
    table: pd.DataFrame,
    scorer: Scorer,
    writer: NoteWriter,
    n: int,
    landmark: pd.Timestamp | None = None,
    out: Path | None = None,
) -> NotesEvaluation:
    landmark = landmark if landmark is not None else table["landmark"].max()
    rows = table[table["landmark"] == landmark].reset_index(drop=True)
    scored = scorer.score(rows).assign(user_id=rows["user_id"].to_numpy())
    top = scored.sort_values("risk_score", ascending=False).head(n)
    results = []
    for _, row in top.iterrows():
        drivers = [{**d, "description": describe(str(d["feature"]))} for d in row["top_drivers"]]
        facts = player_facts(
            int(row["user_id"]), float(row["probability"]), bool(row["flagged"]), drivers
        )
        results.append(writer.write(facts))
    if out is not None:
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w") as fh:
            for uid, r in zip(top["user_id"], results, strict=True):
                fh.write(json.dumps({"user_id": int(uid), **r.model_dump()}) + "\n")
    return NotesEvaluation(results, pd.Timestamp(landmark))


def evaluation_markdown(ev: NotesEvaluation, writer_name: str) -> str:
    n = len(ev.results)
    attempted = n - ev.sources.get("template", 0)
    passed = ev.sources.get("claude", 0)
    rate = f"{passed / attempted:.0%} ({passed}/{attempted})" if attempted else "n/a (template)"
    cost = ev.cost_usd()
    viol = "\n".join(f"| {k} | {v} |" for k, v in ev.violations.most_common()) or "| none | 0 |"
    tokens = [r.output_tokens for r in ev.results if r.output_tokens is not None]
    return f"""# Agent-note evaluation

Generated by `ttr notes eval`. Writer: **{writer_name}**. Landmark {ev.landmark:%Y-%m-%d},
top {n} players by risk. Aggregate only; per-player notes are written to a separate JSONL file.

| | |
|---|---|
| Notes written | {n} |
| LLM notes that passed the guard | {rate} |
| Fell back to the template | {ev.sources.get("template_fallback", 0)} |
| Mean output tokens per LLM note | {f"{sum(tokens) / len(tokens):.0f}" if tokens else "n/a"} |
| Estimated cost | {f"${cost:.4f} (${cost / n:.5f} per note)" if cost is not None else "n/a"} |

## Guard violations

| Violation | Count |
|---|---|
{viol}
"""
