"""Build the EDA / replication report: figures plus a Markdown summary."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from ttr.analysis.figures import structure_figure, trajectories_figure
from ttr.analysis.replication import DFAResult, assign_index_dates, run_replication
from ttr.analysis.trajectories import monthly_trajectories, player_months
from ttr.labels import get_definition, label_status


@dataclass(frozen=True)
class EDAOutputs:
    report: Path
    figures: list[Path]
    results: list[DFAResult]


def _pct(x: float) -> str:
    return f"{x:.0%}"


def _trajectory_rows(traj: pd.DataFrame, months: tuple[int, ...]) -> str:
    t = traj.set_index(["group", "month"])
    share = {k: float(v) for k, v in t["active_share"].items()}
    days = {k: float(v) for k, v in t["bet_days_per_player"].items()}
    lines = [
        "| Month | Cases betting | Controls betting | Case betting days | Control betting days |",
        "|---|---|---|---|---|",
    ]
    for m in months:
        lines.append(
            f"| {m:+d} | {_pct(share[('case', m)])} | {_pct(share[('control', m)])} "
            f"| {days[('case', m)]:.1f} | {days[('control', m)]:.1f} |"
        )
    return "\n".join(lines)


# First RG events on accounts that were already closed or self-excluded (codebook Appendix 3).
ALREADY_CLOSED = {2: "Account re-opened after closure", 16: "Account remains closed"}


def _closed_rows(shares: dict[str, tuple[int, pd.Series]], months: tuple[int, ...]) -> str:
    lines = [
        "| First RG event | n | " + " | ".join(f"{m:+d}" for m in months) + " |",
        "|---|---|" + "---|" * len(months),
    ]
    for label, (n, share) in shares.items():
        cells = " | ".join(_pct(share.get(m, 0.0)) for m in months)
        lines.append(f"| {label} | {n} | {cells} |")
    return "\n".join(lines)


def render_markdown(
    results: list[DFAResult],
    traj: pd.DataFrame,
    closed: dict[str, tuple[int, pd.Series]],
    figure_dir: str,
) -> str:
    by = {r.name: r for r in results}
    full, pre, prim = by["full_history"], by["pre_index"], by["pre_index_primary"]
    top_pre = ", ".join(f"`{n}`" for n in pre.structure.index[:4])
    table = "\n".join(
        f"| {label} | {r.n_cases:,} / {r.n_controls:,} | {r.cv_auc:.3f} | {_pct(r.cv_accuracy)} |"
        for label, r in [
            ("Whole history, all cases (paper's design)", full),
            ("Before intervention only, all cases", pre),
            ("Before intervention only, harm-onset cases", prim),
        ]
    )
    return f"""# Exploratory analysis and replication

Generated by `ttr eda`. Cohort and cleaning rules: [docs/data.md](../docs/data.md).

## 1. Replication of Gray, LaPlante & Shaffer (2012)

The paper compared RG cases and matched controls with a discriminant function analysis (DFA) on
27 betting indices (nine each for fixed-odds, live-action and casino betting) aggregated over each
player's **whole history**. Recomputing the indices from the cleaned daily data reproduces the
paper's published values exactly for at least 95% of players on every index.

Re-running the DFA (linear discriminant analysis on square-root-transformed indices, 5-fold
cross-validated):

| Analysis | Cases / controls | AUC | Accuracy |
|---|---|---|---|
{table}

**The paper's main finding replicates:** the indices most correlated with the discriminant score are
measures of live-action betting intensity. Before intervention, the top four are {top_pre}.

**But the paper's design looks ahead.** Whole-history indices include betting *after* the
intervention. Restricting each player to activity before their index date (a case's first RG
event; for a control, the RG date of a case with the same first-deposit date) lowers AUC from
{full.cv_auc:.2f} to {pre.cv_auc:.2f}. Most of the separation was available in time to act on,
which is what an early-warning model needs, but a model evaluated on whole-history features
would overstate its usefulness.

Restricting cases to harm-onset events (the project's primary label, which drops accounts that
were already closed and non-harm events; see section 2) gives AUC {prim.cv_auc:.2f}.

![Structure coefficients]({figure_dir}/structure_coefficients.png)

## 2. Activity in the months before intervention

### Already-closed accounts are not harm onset

For many cases the first RG event in the study window concerns an account that was **already
closed or self-excluded**: either it was re-opened, or a request to re-open was refused. Their
activity shows the exclusion period directly. Almost none of them bet in the six months before
the event:

Share of players who bet, by month relative to the event:

{_closed_rows(closed, (-9, -7, -6, -3, -1, 0))}

These players' harm began before the window, so they are prevalent rather than incident cases.
The primary label (`configs/labels.yaml`, ADR 0002) excludes them, and the rest of this section
uses harm-onset cases only.

### Harm-onset cases escalate before intervention

Aligning every player on their index date shows that cases differ from controls throughout, and
that their activity **escalates in the last two to three months** before intervention:

{_trajectory_rows(traj, (-12, -6, -3, -2, -1, 0, 3))}

![Monthly trajectories]({figure_dir}/trajectories.png)

Notes:
- Month 0 starts on the intervention date, so it already contains post-intervention activity.
- Sportsbook intensity (median bets per betting day) is roughly 2.5x higher for cases but does
  not rise before intervention. The early signal is in *how often* players bet, not how much
  per day.

## 3. Implications for modelling

1. Features must be computed strictly from activity before the scoring date (landmark design).
2. Recent change matters: the last 1-3 months carry signal beyond long-run levels, so features
   should include short windows and ratios of recent to long-run activity.
3. Live-action betting and betting frequency are the strongest single signals. The rule baseline
   should use them.
4. Label choice changes the signal: already-closed accounts look like *de-escalation* before
   their event. Mixing them into the outcome would teach a model that stopping betting is a
   risk signal.
"""


def build_eda_report(
    daily: pd.DataFrame, players: pd.DataFrame, out_dir: Path, seed: int = 0
) -> EDAOutputs:
    cohort = players[players["exclusion_reason"].isna()]
    results = run_replication(daily, players, seed)
    index_dates = assign_index_dates(cohort, seed)

    status = label_status(cohort, get_definition("primary"))
    harm_cohort = cohort[status != "excluded"]
    traj = monthly_trajectories(daily, harm_cohort, index_dates)

    closed: dict[str, tuple[int, pd.Series]] = {}
    for code, label in ALREADY_CLOSED.items():
        ids = cohort.loc[(cohort["intervention_type_first"] == code).fillna(False), "user_id"]
        pm = player_months(daily, index_dates.reindex(ids), 12, 1).reset_index()
        closed[label] = (len(ids), pm.groupby("month")["user_id"].nunique() / max(len(ids), 1))

    fig_dir = out_dir / "figures"
    figures = [
        structure_figure(results, fig_dir / "structure_coefficients.png"),
        trajectories_figure(traj, fig_dir / "trajectories.png"),
    ]
    report = out_dir / "eda.md"
    report.write_text(render_markdown(results, traj, closed, "figures"))
    return EDAOutputs(report, figures, results)
